# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

movies = [{:title => 'Coco',:description => 'En el pequeño pueblo de Santa Cecilia vive Miguel, un niño de 12 años que sueña con ser un músico como su famoso ídolo Ernesto de la Cruz, un popular compositor/cantante y estrella de cine que murió cuando fue aplastado por una campana en una presentación en vivo. Sin embargo la familia de Miguel tiene una larga y estricta restricción hacia la música que se remonta generaciones en el pasado cuando la tatarabuela de Miguel fue abandonada por un músico que decidió dejar su familia con tal de seguir sus sueños',:release_date => '07/15/2017'.to_date, :slug => 'Coco', :image => 'http://t1.gstatic.com/images?q=tbn:ANd9GcTr_qI5j_Grsqc1rfxadECrGKPTwxogqua_CMEUD_iWYivDY97R'},
          {:title => 'Spider-Man: Homecoming',:description => 'Dos meses después de los terribles acontecimientos en Capitán América: Civil War, Peter Parker, con la ayuda de su mentor Tony Stark, trata de equilibrar su vida como un estudiante de secundaria en Queens, y su lucha contra el crimen como Spider-Man mientras se enfrenta a una nueva amenaza, el Buitre.', :release_date =>'07/07/2017'.to_date, :slug =>'spider_man_homecoming', :image =>'https://orig00.deviantart.net/56bb/f/2017/145/4/f/spider_man_homecoming_improved_version_by_themadbutcher-dbafc4m.jpg'},
          {:title => 'It', :description => 'Son los años 80 en el pequeño pueblo de Derry, en el estado de Maine. En él vive una panda de siete niños conocidos como "El club de los perdedores", que debe enfrentarse a sus problemas cotidianos con los matones de la escuela. Pero su vida da un giro inesperado cuando, durante el verano, una gran amenaza se cierne sobre ellos después de que una oleada de extrañas muertes provoquen el pánico y el terror entre los habitantes del lugar.', :release_date=> '09/07/2017'.to_date, :slug => 'it', :image =>'http://bloghorror.com/wp-content/uploads/2017/04/1e45555a0c82ebcf5633a4239a27cf2b.jpg' },
          {:title => 'Thor: Ragnarok', :description => 'Thor está preso al otro lado del universo y con su poderoso martillo destruido en mil pedazos, ahora se enfrenta a una carrera contra el tiempo. Su objetivo es volver a Asgard y parar el Ragnarök (la batalla del fin del mundo), antes de que esto signifique la destrucción de su planeta natal y el fin de la civilización asgardiana a manos de una todopoderosa y nueva amenaza, la diosa asgardiana de la muerte, Hela. Pero, primero deberá sobrevivir a una competición de gladiadores, en el planeta Saakar, donde se enfrentará a su compañero de Los Vengadores, Hulk.', :release_date =>'11/02/2017'.to_date}, :slug => 'thor_ragnarok', :image=>'https://pics.filmaffinity.com/thor_ragnarok-115636540-large.jpg'},
          {:title => ' Wonder Woman ',:description =>'Antes de ser Wonder Woman (Gal Gadot) era Diana, princesa de las Amazonas, entrenada para ser una guerrera invencible. Diana fue criada en una isla paradisíaca protegida. Hasta que un día un piloto norteamericano (Chris Pine), que tiene un accidente y acaba en sus costas, le habla de un gran conflicto existente en el mundo [Primera Guerra Mundial]. Diana decide salir de la isla convencida de que puede detener la terrible amenaza. Mientras lucha junto a los hombres en la guerra que acabará con todas las guerras, Diana descubre todos sus poderes y su verdadero destino.', :release_date => '05/15/2017'.to_date,:slug=>'wonder_woman',:image =>'https://pics.filmaffinity.com/wonder_woman-552748603-large.jpg'},
          {:title => 'Pirates of the Caribbean: Dead Men Tell No Tales ', :description=>'El capitán Jack Sparrow se enfrentará a un grupo de piratas-fantasma comandados por una de sus viejas némesis, el terrorífico capitán Salazar, recién escapado del Triángulo de las Bermudas. La única posibilidad de Sparrow para salir con vida es encontrar el legendario Tridente de Poseidón, un poderoso artefacto que le da a su poseedor el control de los mares.', :release_date=>'05/11/2017'.to_date, :slug=>'pirates_of_the_caribbean_dead_men_tell_no_tales', :image=>'https://pics.filmaffinity.com/pirates_of_the_caribbean_dead_men_tell_no_tales-750385069-large.jpg'},
          {:title => 'Guardians of the Galaxy Vol. 2', :description=>'Continúan las aventuras del equipo en su travesía por los confines del cosmos. Los Guardianes deberán luchar para mantener unida a su nueva familia mientras intentan resolver el misterio de los verdaderos orígenes de Peter Quill. Viejos rivales se convertirán en nuevos aliados, y queridos personajes de los cómics clásicos acudirán en ayuda de nuestros héroes a medida que el universo cinematográfico de Marvel continúa expandiéndose.', :release_date=>'04/19/2017'.to_date,:slug=>'guardians_of_the_galaxy_vol_2', :image=>'https://pics.filmaffinity.com/guardians_of_the_galaxy_vol_2-755407784-large.jpg'},
          {:title => 'Logan', :description=>'Sin sus poderes, por primera vez, Wolverine es verdaderamente vulnerable. Después de una vida de dolor y angustia, sin rumbo y perdido en el mundo donde los X-Men son leyenda, su mentor Charles Xavier lo convence de asumir una última misión: proteger a una joven que será la única esperanza para la raza mutante.', :release_date=>'03/01/2017'.to_date,:slug=>'logan', :image=>'https://pics.filmaffinity.com/logan-528968427-large.jpg' },
          {:title => 'Alien: Covenant ', :description=> 'Durante un viaje en el espacio rumbo a un remoto planeta al otro lado de la galaxia para colonizarlo, la tripulación de la nave 'Covenant' descubre una señal proveniente de lo que creen puede ser un paraíso inexplorado, y que resulta ser un mundo oscuro y hostil.', :release_date=>'05/04/2017'.to_date,:slug =>'alien_covenant', :image=>'https://pics.filmaffinity.com/alien_covenant-271063602-large.jpg'},
          {:title => 'War for the Planet of the Apes', :description => 'César y sus monos son forzados a encarar un conflicto mortal contra un ejército de humanos liderado por un brutal coronel. Después de sufrir pérdidas enormes, César lucha con sus instintos más oscuros en una búsqueda por vengar a su especie. Cuando finalmente se encuentren, Cesar y el Coronel protagonizarán una batalla que pondrá en juego el futuro de ambas especies y el del mismo planeta.', :release_date => '07/10/2017'.to_date, :slug => 'war_for_the_planet_of_the_apes', :image => 'https://pics.filmaffinity.com/war_for_the_planet_of_the_apes-586054910-large.jpg'},
          {:title => 'Murder on the Orient Express'}, :description =>'Durante un viaje en el legendario tren Orient Express, el detective belga Hercules Poirot investiga un asesinato cometido en el trayecto, y a resultas del cual todos los pasajeros del tren son sospechosos del mismo.', :release_date => '11/03/2017'.to_date, :slug => 'murder_on_the_orient_express', :image => 'https://pics.filmaffinity.com/murder_on_the_orient_express-328389244-large.jpg'},
          {:title => 'Dunkirk', :description => 'Año 1940, en plena II Guerra Mundial. En las playas de Dunkerque, cientos de miles de soldados de las tropas británicas y francesas se encuentran rodeados por el avance del ejército alemán, que ha invadido Francia. Atrapados en la playa, con el mar cortándoles el paso, las tropas se enfrentan a una situación angustiosa que empeora a medida que el enemigo se acerca.', :release_date => '07/13/2017'.to_date, :slug => 'dunkirk', :image => 'https://pics.filmaffinity.com/dunkirk-461720087-large.jpg'},
          {:title => 'Blade Runner 2049', :description => 'Treinta años después de los eventos del primer film, un nuevo blade runner, K (Ryan Gosling) descubre un secreto largamente oculto que podría acabar con el caos que impera en la sociedad. El descubrimiento de K le lleva a iniciar la búsqueda de Rick Deckard (Harrison Ford), un blade runner al que se le perdió la pista hace 30 años.', :release_date => '10/03/2017'.to_date, :slug => 'blade_runner_2049', :image => 'https://pics.filmaffinity.com/blade_runner_2049-681477614-mmed.jpg'},
          {:title => 'The Mummy', :description => 'A pesar de estar enterrada en una tumba en lo más profundo del desierto, una antigua princesa (Sofia Boutella) cuyo destino le fue arrebatado injustamente, se despierta en la época actual, trayendo consigo una maldición que ha crecido hasta límites insospechados con el paso de miles de años.', :release_date => '06/09/2017'.to_date, :slug => 'the_mummy', :image => 'https://pics.filmaffinity.com/the_mummy-692544562-mmed.jpg'},
          {:title => 'The Fate of the Furious', :description => 'Con Dom y Letty de luna de miel, Brian y Mia fuera del juego y el resto de la pandilla exonerada de todo cargo, el equipo está instalado en una vida aparentemente normal. Pero cuando una misteriosa mujer (Theron) seduce a Dom (Diesel) para regresar nuevamente al mundo del crimen, se ve incapaz de rechazar la oportunidad, traicionando así a todo el mundo cercano a él. A partir de ese momento todos se enfrentarán a pruebas como nunca antes habían tenido. Desde las costas de Cuba y las calles de Nueva York hasta las llanuras del mar de Barents en el océano Ártico, nuestra fuerza de élite recorrerá el globo para impedir que un anarquista desencadene el caos en el mundo... y por supuesto para traer de vuelta a casa al hombre que les hizo una familia.', :release_date => '04/04/2017'.to_date, :slug =>'the_fate_of_the_furious', :image => 'https://pics.filmaffinity.com/the_fate_of_the_furious-720946563-mmed.jpg'},
          {:title => 'Saw VIII', :description => 'Jigsaw está de vuelta. En esta ocasión atrapará a cinco personas y las enfrentará en una serie de juegos sangrientos como castigo por sus delitos. Al mismo tiempo tiene lugar una investigación en la que científicos forenses tratan de encontrar y capturar al asesino, con la sospecha de que alguien del equipo puede ser el responsable.', :release_date => '10/26/2017'.tod_date, :slug => 'saw_viii', :image => 'https://pics.filmaffinity.com/jigsaw-550599251-mmed.jpg'},
          {:title => 'Suburbicon', :description => 'Un misterio criminal ambientado en un tranquilo pueblo familiar de Suburbicon durante los años 50, donde lo mejor y lo peor de la humanidad se ve reflejado en las vidas de la gente corriente. Cuando un allanamiento de morada se vuelve mortal, una familia aparentemente perfecta empezará a hacer uso del chantaje, la venganza y la traición.', :release_date => '10/27/2017'.to_date, :slug => 'suburbicon', :image => 'https://pics.filmaffinity.com/suburbicon-269511033-mmed.jpg'},
          {:title => 'Beauty and the Beast', :description => 'Adaptación en imagen real del clásico de Disney "La bella y la bestia", que cuenta la historia de Bella (Emma Watson), una joven brillante y enérgica, que sueña con aventuras y un mundo que se extiende más allá de los confines de su pueblo en Francia. Independiente y reservada, Bella no quiere saber nada con el arrogante y engreído Gastón, quien la persigue sin descanso. Todo cambia un día cuando su padre Maurice (Kevin Kline) es encarcelado en el castillo de una horrible Bestia, y Bella se ofrece a intercambiarse con su padre y queda recluida en el castillo. Rápidamente se hace amiga del antiguo personal del lugar, que fue transformado en objetos del hogar tras una maldición lanzada por una hechicera.', :release_date => '03/16/2017'.to_date, :slug => 'beauty_and_the_beast', :image => 'https://pics.filmaffinity.com/beauty_and_the_beast-281766413-mmed.jpg'},
          {:title => 'Cars 3', :description => 'Sorprendido por una nueva generación de corredores ultrarrápidos, el legendario Rayo McQueen queda relegado repentinamente del deporte que tanto ama. Para retomar su carrera, va a necesitar la ayuda de una joven mecánica de carreras, Cruz Ramírez, que tiene su propio plan para ganar, además de la inspiración del fallecido Fabuloso Hudson Hornet y un par de giros inesperados. ¡Y para probar que el nº95 no está ni mucho menos acabado, el campeón tendrá que poner a prueba su valía en el gran circuito de la Copa Piston!', :release_date => ' 06/15/2017'.to_date, :slug => 'cars_3', :image => 'https://pics.filmaffinity.com/cars_3-755380967-mmed.jpg'}
        
]

movies.each do |movie|
  Movie.find_or_create_by(movie)
end

premieres = [
  {title: 'Insidious: The Last Key', prem_date: Date.strptime("01/05/2018", '%m/%d/%Y')},
  {title: 'Day of the dead: Bloodline', prem_date: Date.strptime("01/05/2018", '%m/%d/%Y')},
  {title: "Molly's Game", prem_date: Date.strptime("12/25/2018", '%m/%d/%Y')},
  {title: "Molly's Game", prem_date: Date.strptime("01/05/2018", '%m/%d/%Y')},
  {title: "Star Wars: The Last Jedi", prem_date: Date.strptime("12/15/2018", '%m/%d/%Y')},
  {title: "Jumanji: Welcome to the Jungle", prem_date: Date.strptime("12/20/2017", '%m/%d/%Y')},
  {title: "Avengers: Infinity War", prem_date: Date.strptime("04/25/2018",'%m,%d%Y')},
  {title: "Black Panther", prem_date: Date.strptime("02/09/2018",'%m,%d%Y')},
  {title: "The new Mutants", prem_date: Date.strptime("04/13/2018", "%m%d%Y")},
  {title: "Untitled Deadpool Sequel", prem_date: Date.strptime("05/31/2018",'%m%d%Y')},
  {title: "Ant-Man and the Wasp", prem_date: Date.strptime("07/06/2018",'%m%d%Y')},
  {title: "Jurassic World: Fallen Kingdom", prem_date: Date.strptime("06/22/2018",'%m%d%Y')},
  {title: "The Incredibles 2", prem_date: Date.strptime("06/14/2018",'%m%d%Y')},
  {title: "Pacific Rim: Insurrección", prem_date: Date.strptime("03/22/2018",'%m%d%Y')},
  {title: "Venom", prem_date: Date.strptime("10/05/2018",'%m%d%Y')},
  {title: "Tom Raider", prem_date: Date.strptime("03/16/2018",'%m%d%Y')},
  {title: "Aquaman", prem_date: Date.strptime("12/21/2018",'%m%d%Y')},
  {title: "Maze Runner: The Death Cure", prem_date: Date.strptime("01/26/2018",'%m%d%Y')},
  {title: "Predator", prem_date: Date.strptime("08/03/2018",'%m%d%Y')},
  {title: "Ready Player One", prem_date: Date.strptime("03/30/2018",'%m%d%Y')}
]

premieres.each do |premier|
  Premiere.create!(premier)
end

=begin
  99.times do |n|
    title = "Película número #{n}"
    year = "200#{n}"
    description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras nisl enim, tempor id ullamcorper vel, posuere eu dui. Ut placerat felis eros, ac sagittis lorem mollis cursus. Aliquam erat volutpat. Integer non risus auctor, imperdiet est tempor, lacinia magna. Vestibulum et ligula quis felis dictum porta. Praesent in turpis semper, finibus nisl eget, convallis metus. Mauris quis maximus eros. Sed dolor nibh, imperdiet ac justo id, bibendum tincidunt neque. Nam dapibus suscipit mattis. Fusce sollicitudin accumsan ligula sed suscipit. Cras."
    Movie.create!(title: title, year: year, description: description)
  end
=end

Admin.create(email: 'admin@homie.mx', password: 'admin123', password_confirmation: 'admin123')
