INSERT INTO "movies"
            ("title",
             "description",
             "release_date",
             "slug",
             "created_at",
             "updated_at")
VALUES      ('Coco',
'En el pequeño pueblo de Santa Cecilia vive Miguel, un niño de 12 años que sueña con ser un músico como su famoso ídolo Ernesto de la Cruz, un popular compositor/cantante y estrella de cine que murió cuando fue aplastado por una campana en una presentación en vivo. Sin embargo la familia de Miguel tiene una larga y estricta restricción hacia la música que se remonta generaciones en el pasado cuando la tatarabuela de Miguel fue abandonada por un músico que decidió dejar su familia con tal de seguir sus sueños',
'2017-07-15 00:00:00',
'coco',
'2017-12-08 09:24:35.782213',
'2017-12-08 09:24:35.782213'),

('Spider-Man: Homecoming',
'Dos meses después de los terribles acontecimientos en Capitán América: Civil War, Peter Parker, con la ayuda de su mentor Tony Stark, trata de equilibrar su vida como un estudiante de secundaria en Queens, y su lucha contra el crimen como Spider-Man mientras se enfrenta a una nueva amenaza, el Buitre.',
'2017-07-07 00:00:00',
'spider-man:-homecoming',
'2017-12-08 09:24:35.998928',
'2017-12-08 09:24:35.998928'),

('It',
'Son los años 80 en el pequeño pueblo de Derry, en el estado de Maine. En él vive una panda de siete niños conocidos como "El club de los perdedores", que debe enfrentarse a sus problemas cotidianos con los matones de la escuela. Pero su vida da un giro inesperado cuando, durante el verano, una gran amenaza se cierne sobre ellos después de que una oleada de extrañas muertes provoquen el pánico y el terror entre los habitantes del lugar.',
'2017-09-07 00:00:00', 
'it', 
'2017-12-08 09:24:36.144228',
'2017-12-08 09:24:36.144228'),

('Wonder Woman',
'Antes de ser Wonder Woman (Gal Gadot) era Diana, princesa de las Amazonas, entrenada para ser una guerrera invencible. Diana fue criada en una isla paradisíaca protegida. Hasta que un día un piloto norteamericano (Chris Pine), que tiene un accidente y acaba en sus costas, le habla de un gran conflicto existente en el mundo [Primera Guerra Mundial]. Diana decide salir de la isla convencida de que puede detener la terrible amenaza. Mientras lucha junto a los hombres en la guerra que acabará con todas las guerras, Diana descubre todos sus poderes y su verdadero destino.',
'2017-05-15 00:00:00', 
'wonder-woman', 
'2017-12-08 09:24:36.308638', 
'2017-12-08 09:24:36.308638'),

